image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5005
    onOpen: ignore

vscode:
  extensions:
    - redhat.mta-vscode-extension
    - redhat.vscode-quarkus@0.0.79
tasks:
  - name: Add Quarkus CLI completion to shell
    before: source <(quarkus completion)
  - name: Pre-warm Maven
    init: mvn -fn dependency:resolve-plugins dependency:resolve dependency:go-offline clean compile package
