image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5005
    onOpen: ignore

vscode:
  extensions:
    - redhat.mta-vscode-extension
tasks:
  - name: Pre-warm Maven
    init: mvn -fn dependency:resolve-plugins dependency:resolve dependency:go-offline clean compile package
